name: expense_tracker_app
description: "A personal finance management app that helps students track their daily expenses, manage budgets, and save money efficiently."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.0.0
  intl: ^0.18.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  animations: ^2.0.7
  introduction_screen: ^3.1.1
  url_launcher: ^6.2.4
  flutter_native_splash: ^2.3.10
  lottie: ^3.0.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  android_12:
    image: assets/splash/splash.png
  web: false
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie_animations/
    - assets/splash/
    - assets/icon/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700